# Define two scrapers
#   1. docker - which collects the matrixes of docker
#   2. eexporter - which collects the matrixes of elasticsearch
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'lambda-monitor'
scrape_configs:
  - job_name: 'elastic-exporter'
    target_groups:
      - targets: ['10.128.0.4:9114', '10.128.0.5:9114', '10.128.0.6:9114']
