version: '3'
services:
  elastic-master:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elastic_master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300

networks:
  elastic:
    driver: bridge
